name = "VecDiff"
uuid = "41399b9e-5faf-4733-b7c1-c9e699c3c810"
authors = ["chengzhengqian-game <chengzhengqian@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
